### ISSUE TITLE
1 Weird bug on touch bar macbook you would never expect

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#218] opened 2017-07-20 03:49 UTC
I get this weird bug where when you close the window with the devtools open, both windows seem to close but then you get this blank window where the main window was open.  Not sure if its something we are doing or an electron bug, but it seems to only happen on a tour bar Mac ` ¯\_(ツ)_/¯`

![weird bug](https://user-images.githubusercontent.com/166301/28399736-b4415d48-6cc3-11e7-99f5-2daa2f8fb06e.gif)

**Comment by ungoldman** [comment] 2017-09-14 16:52
definitely electron bug, have seen it in another electron app. seems to be the window can't close until it loses focus on the devtools are closed.

**Comment by ungoldman** [comment] 2017-09-17 19:13
Going to close this since I've seen it in other electron apps and it's only reproducible when using devtools.

**Closed by ungoldman** 2017-09-17 19:13 UTC
